language: python

python:
    - "2.7"

install: "pip install -r requirements.txt"

notifications:
    email:
        - daniel.j.dufour@gmail.com

script: python -m unittest location_extractor.tests.test
